"""Schema version constants."""

CONFIG_SCHEMA_VERSION = "1.0"
REPLAY_SCHEMA_VERSION = "1.0"
ACTION_SCHEMA_VERSION = "1.0"
OBSERVATION_SCHEMA_VERSION = "1.0"
PROFILE_SCHEMA_VERSION = "1.0"
METRICS_SCHEMA_VERSION = "1.0"
