"""Deterministic fallback rules for language-to-profile parsing."""

from __future__ import annotations

import re

from combatrl.nlp.validation import (
    PROFILE_AXIS_FIELDS,
    balanced_profile,
    detect_unsupported_requests,
    validate_parsed_profile,
)
from combatrl.schemas.nlp import BehaviorProfileParseResult
from combatrl.schemas.profiles import BehaviorProfile

RuleAdjustment = dict[str, float]

RULE_GROUPS: tuple[tuple[tuple[str, ...], RuleAdjustment], ...] = (
    (
        ("aggressive", "aggressively", "attack", "push", "dive", "engage"),
        {"aggression": 0.25, "caution": -0.10},
    ),
    (
        ("defensive", "safe", "survive", "stay alive", "avoid dying"),
        {"caution": 0.30, "aggression": -0.15, "greed": -0.10},
    ),
    (
        ("protect", "peel", "guard", "defend ally", "protect teammate"),
        {"protectiveness": 0.35, "cohesion": 0.15},
    ),
    (
        ("kite", "keep distance", "back up", "avoid close combat"),
        {"spacing": 0.35, "caution": 0.10},
    ),
    (("focus", "focus fire", "same target"), {"focus_fire": 0.35}),
    (
        ("chase", "finish", "secure kill", "low health enemy", "low health enemies"),
        {"greed": 0.25, "aggression": 0.10},
    ),
    (("group", "stay together", "stay near ally"), {"cohesion": 0.30}),
)
BALANCED_TERMS = ("balanced", "default", "normal")


def apply_rule_based_profile_adjustments(
    command: str,
    base_profile: BehaviorProfile,
) -> tuple[BehaviorProfile, list[str], list[str]]:
    """Apply deterministic supported phrase rules to a base profile."""
    candidate = base_profile.model_dump(mode="python")
    matched_rules: list[str] = []
    unsupported_requests = detect_unsupported_requests(command)
    normalized = command.lower()

    if any(_contains_phrase(normalized, phrase) for phrase in BALANCED_TERMS):
        candidate = balanced_profile().model_dump(mode="python")
        matched_rules.append("balanced")

    for phrases, adjustments in RULE_GROUPS:
        if not any(_contains_phrase(normalized, phrase) for phrase in phrases):
            continue
        matched_rules.append(phrases[0])
        for axis, delta in adjustments.items():
            candidate[axis] = float(candidate[axis]) + delta

    validation_candidate = {
        "command": command,
        "unsupported_requests": unsupported_requests,
        **{axis: candidate[axis] for axis in PROFILE_AXIS_FIELDS},
        "notes": "Generated by deterministic fallback rules.",
    }
    result = validate_parsed_profile(
        validation_candidate,
        base_profile=base_profile,
        parser_source="rules",
    )
    if result.profile is None:
        msg = "; ".join(result.errors) or "rule-based profile validation failed"
        raise ValueError(msg)
    return result.profile, unsupported_requests, matched_rules


def parse_with_rules(
    command: str,
    base_profile: BehaviorProfile | None = None,
) -> BehaviorProfileParseResult:
    """Parse a command using deterministic keyword rules only."""
    if not command.strip():
        return BehaviorProfileParseResult(
            success=False,
            command=command,
            profile=None,
            errors=["command must be non-empty"],
            unsupported_requests=[],
            parser_source="rules",
        )

    base = base_profile or balanced_profile()
    unsupported_requests = detect_unsupported_requests(command)
    profile, unsupported_requests, matched_rules = apply_rule_based_profile_adjustments(
        command, base
    )
    if not matched_rules:
        if unsupported_requests:
            return BehaviorProfileParseResult(
                success=False,
                command=command,
                profile=None,
                errors=["no supported tactical intent found"],
                unsupported_requests=unsupported_requests,
                parser_source="rules",
            )
        return BehaviorProfileParseResult(
            success=False,
            command=command,
            profile=None,
            errors=["no supported tactical intent found"],
            unsupported_requests=[],
            parser_source="rules",
        )

    return BehaviorProfileParseResult(
        success=True,
        command=command,
        profile=profile,
        errors=[],
        unsupported_requests=unsupported_requests,
        parser_source="rules",
        notes=(
            "Unsupported requests are reported as warnings; supported intents changed profile axes."
        ),
    )


def _contains_phrase(normalized_command: str, phrase: str) -> bool:
    escaped = re.escape(phrase.lower())
    return re.search(rf"(?<![a-z0-9]){escaped}(?![a-z0-9])", normalized_command) is not None


__all__ = ["apply_rule_based_profile_adjustments", "parse_with_rules"]
